### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Dig-Doug** [ddunbar/PDSample#2]
Would it be possible to use one of the [open source licenses](https://choosealicense.com/) for this project? 

I'm hesitant to use this code with the current license because it's unclear exactly what the terms are.

Thanks!

**Comment by ddunbar** [comment]
A public domain release is more open than almost all licenses, at this time I’m probably not going to change the license although I can understand where you are coming from.

**Comment by Dig-Doug** [comment]
Thanks for the quick response. I did a bit of reading and it seems that worldwide it is quite difficult to release things into the public domain. However, there are [some licenses](https://creativecommons.org/share-your-work/public-domain/cc0/) that are meant to solve the legal issues. Would that work?

**Comment by ddunbar** [comment]
Adopted unlicense explicitly, hopefully that meets your needs

**Comment by Dig-Doug** [comment]
Thanks!
